version: '3.8'

services:
  mysql-m:
    image: mysql:8.0
    container_name: mysql-m
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - mysql-cluster

  mysql-s1:
    image: mysql:8.0
    container_name: mysql-s1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./slave1/data:/var/lib/mysql
      - ./slave1/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3306"
    networks:
      - mysql-cluster

  mysql-s2:
    image: mysql:8.0
    container_name: mysql-s2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./slave2/data:/var/lib/mysql
      - ./slave2/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3308:3306"
    networks:
      - mysql-cluster

networks:
  mysql-cluster:
    driver: bridge
